dist: xenial
language: python
cache:
  directories:
    - $HOME/.cache/pip
branches:
  only:
  - master
  - 2.6
notifications:
  email: false

matrix:
  include:
    # pypy takes longer, start it first
    - python: "pypy2.7-7.1.1"
      env: CRYPTO_VER=2.4.2
    - python: "pypy3.5-7.0"
      env: CRYPTO_VER=2.6.1

    - python: "2.7"
      env: CRYPTO_VER=1.6
    - python: "2.7"
      env: CRYPTO_VER=2.4.2 USE_K5TEST=yes
    - python: "3.4"
      env: CRYPTO_VER=1.6
    - python: "3.4"
      env: CRYPTO_VER=2.4.2
    - python: "3.5"
      env: CRYPTO_VER=2.6.1 USE_K5TEST=yes
    - python: "3.6"
      env: CRYPTO_VER=2.4.2
    - python: "3.7"
      env: CRYPTO_VER=2.6.1

install:
  - pip install cryptography==$CRYPTO_VER PyNaCl
  # Self-install for setup.py-driven deps
  - pip install -e .
  # Dev (doc/test running) requirements
  - pip install -r dev-requirements.txt
  # for gssapi tests
  - |
    if [ -n "$USE_K5TEST" ]; then
      sudo apt-get --assume-yes --quiet install libkrb5-dev krb5-admin-server \
                                                krb5-kdc krb5-user krb5-multidev
      pip install gssapi==1.5.1 pyasn1==0.4.5 k5test==0.9.2
    fi
script:
  - flake8
  - pytest -v
